[build]
builder = "nixpacks"
buildCommand = "mkdir -p /app/config && echo 'Creating config directory...'"

[deploy]
startCommand = "python main.py"

[variables]
BOT_TOKEN = "7747855846:AAFWjqqZXNBpwFFjrAQi3fjT5qwBbjcJCNs"
ANNOUNCEMENT_CHANNEL = "@LanguagesTranslator"